# Generated by Django 2.1.7 on 2019-03-09 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=16)),
                ('pwd', models.CharField(max_length=16)),
                ('age', models.IntegerField()),
                ('hobby', models.CharField(max_length=32)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
